### ISSUE TITLE
Add Travis deploying GitHub Releases 

### ISSUE THREAD

**Issue by Aleyasen** [surveyjs/surveyjs#118]
It will be nice if the latest artifacts of the master branch will be available instantly after Travis build. I edited the .travis.yml to do it. 

```yml
language: node_js
node_js:
  - "4"

before_script:
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g typings
script:
  - typings install
  - gulp copyfiles
  - gulp makedist
  - gulp test_ci
before_deploy: "tar -zcvf surveyjs.tar.gz dist"
deploy:
  provider: releases
  api_key:
      secure: "<encrypted-token>"
  file:
    - "surveyjs.tar.gz"
  skip_cleanup: true
  on:
    tags: true
``` 

The easiest way to generate ```<encrypted-token>``` explained here: http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519

Note that deploying GitHub Releases works only for tags, not for branches.
