### ISSUE TITLE
question titles and inputs alignment

### ISSUE THREAD

**Issue by moldoe** [surveyjs/surveyjs#1264]
When titlePosition is set to left, is there a way to align the start of the inputs? See attached image.

Thanks,

Daniel
![image](https://user-images.githubusercontent.com/23000474/43666856-91bbd39c-9743-11e8-9a62-1557238768d4.png)

**Comment by dmitrykurmanov** [comment]
@moldoe hello
It could be achive via the css:
```css
.title-left {
  width: 30%;
  text-align: right;
}
```
We've created an example for you: https://plnkr.co/edit/7YyVmX8JGYTnB44IMXOV?p=preview 
Could you please check it?
