### ISSUE TITLE
Change sv_panel_icon for collapse/expand panel functionality

### ISSUE THREAD

**Issue by kholibri3** [surveyjs/surveyjs#1373]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

The arrow icon that you click to collapse and expand a panel has the sv_panel_icon class but does not seem to contain an `<img>` tag of the arrow.

### What is the expected behavior?

The icon is a .png/svg image (`img` tag) that can be customized.

If there is any way to customize the arrow icon, suggestions would be much appreciated!

**Comment by tsv2013** [comment]
Here are the CSS rules defining the `sv_panel_icon` appearance. You can override them.

```CSS
.sv_p_title .sv_panel_icon.sv_expanded::before {
    transform: rotate(180deg);
}
<style>…</style>
.sv_p_title .sv_panel_icon::before {
    content: "";
    display: inline-block;
    background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiP…NzPSJzdDAiIHBvaW50cz0iMiwyIDAsNCA1LDkgMTAsNCA4LDIgNSw1ICIvPg0KPC9zdmc+DQo=);
    background-repeat: no-repeat;
    background-position: center center;
    padding: 0.5em;
}
```
