### ISSUE TITLE
Custom styles on correct answers

### ISSUE THREAD

**Issue by Gytisla** [surveyjs/surveyjs#1512]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the expected behavior?

Is it possible to style the correct answers of `Radio Group`, when `mode = 'display'` is set?

![image](https://user-images.githubusercontent.com/38819776/51252035-aa06c200-1992-11e9-9a76-5cdc35dbee4e.png)

**Comment by dmitrykurmanov** [comment]
Hello! You could achieve it via the css:

```css
.sv_q_radiogroup.checked {
   background: #yourcolorhere;
}
```
here an example: https://plnkr.co/edit/QUltkVRWHOz88ntfsKq6?p=preview
